# Generated by Django 6.0.2 on 2026-03-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_foodlog_carbs_foodlog_fats_foodlog_protein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20),
        ),
    ]
